open module com.mastfrog.portable.crypto {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.crypto;
    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.function;
    requires transitive com.mastfrog.util.preconditions;
    requires transitive com.mastfrog.util.streams;
    requires transitive com.mastfrog.util.strings;
    requires transitive com.mastfrog.util.time;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
