// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.portable.crypto {
    exports com.mastfrog.crypto;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.misc;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/util-streams-3.0.0-dev
    requires com.mastfrog.streams;

    // Inferred from source scan

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;

    // Inferred from source scan

    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;

    // Inferred from source scan

    // Sibling com.mastfrog/util-function-3.0.0-dev
    requires com.mastfrog.util.function;

    // Inferred from test-source-scan
    requires transitive junit;

}
